### Obtener un usuario
POST http://localhost:3200/turista/solicitudViaje HTTP/1.1
Content-Type: application/json

{
    "agencia": "avianca",
    "origen": "Guatemala",
    "destino": "Los Angeles",
    "dias": "15",
    "precio": "3500",
    "username": "natalia"
}